### ISSUE TITLE
SubString{ASCIIString} and Array::SubString{ASCIIString}

### ISSUE THREAD

**Issue by brandonkmiller** [JuliaLang/Compat.jl#286]
in one of my packages: https://github.com/brandonkmiller/NMEA.jl I had dep warns (v0.5) for ASCIIString and used Compat.jl to safely support String. However in doing so I broke the package for 0.4 do to the type declaration in function Arguments for Array::SubString{String} and SubString{String} with the following error: 
```
ERROR: LoadError: MethodError: `get_system` has no method matching get_system(::SubString{ASCIIString})
```

Can SubString{String}/SubString{ASCIIString} be added to Compat?

**Comment by nalimilan** [comment]
That's not an issue with Compat, that's just type invariance (Google for that and you'll find explanations in the mailing list archives).

In your case, the best solution is to drop the `{String}` parameter, since a `SubString` can only be based on an `AbstractString` anyway. Overtyping signatures isn't a good idea. For the `Array{SubString{String}}` method, you need to do  `get_system{T<:SubString}(items::Array{T}, ...)`. (BTW, this one should probably be `AbstractArray` too.)

**Comment by brandonkmiller** [comment]
ty!
