### ISSUE TITLE
Capitalization of numeric type constructors

### ISSUE THREAD

**Issue by sjkelly** [JuliaLang/Compat.jl#32]
Running some libraries through Lint I see the following info:

```
INFO   In 0.4+, replace float64() with Float64()
INFO   In 0.4+, replace int64() with Int64()
```

Should these be aliased?

Related:
https://github.com/tonyhffong/Lint.jl/issues/57

**Comment by garborg** [comment]
With the deprecations that have come up recently on 0.4 for the lowercase versions those types and `Bool`, lots of IO code effectively hangs for me on 0.4 (even just running package tests -- small files).

For personal  or new libraries, we're at the point where I've stopped supporting 0.3 because of the effort, but I'm talking about `DataFrames`, `GZip`, etc., here, so that's probably not an option quite yet. @ivarne's solution sounds reasonable, but anything would be great.

**Comment by garborg** [comment]
Ooops, looks like this was taken care of in #50. Sorry for the noise, and thanks, @jakebolewski!

**Comment by jakebolewski** [comment]
The pause due to IO is a bug with the task switching code, not expected behavior.  I think @andreasnoack was seeing this behavior as well.

**Comment by garborg** [comment]
Okay, that makes more sense. Thanks.
