### ISSUE TITLE
`Compat.Unicode.normalize` refers to wrong functions

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaLang/Compat.jl#506]
```
julia> methods(Compat.Unicode.normalize)
# 2 methods for generic function "normalize":
normalize(v::AbstractArray{T,1} where T) in Base.LinAlg at linalg/generic.jl:1367
normalize(v::AbstractArray{T,1} where T, p::Real) in Base.LinAlg at linalg/generic.jl:1367
```

**Comment by stevengj** [comment]
Since this was renamed from `normalize_string` in the same PR that created the `Unicode` module (JuliaLang/julia#25021), the fix is simple: in the [`VERSION < v"0.7.0-DEV.2915"` case](https://github.com/JuliaLang/Compat.jl/blob/7d4f15c3fa0412a44ccee2d6f98fd09498d823d1/src/Compat.jl#L1030-L1058), just add:
```
const normalize = normalize_string
```
and add `normalize` to the exports.
