### ISSUE TITLE
Julia 0.2 compatibility breakage

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/Compat.jl#60]
This was broken by 8759ca58dd7ed976a6934b4af5d5459dcc2f9b01

It would be nice to continue to support 0.2 at least until 0.4 is released, but it is a problem that no one is testing with Julia 0.2 anymore.  Can we update Travis to test with 0.2?

**Comment by tkelman** [comment]
If we can attempt to bring back 0.2 compatibility, I agree it would be most effective to do so here.

We didn't have the infrastructure to make generic Linux binaries with 0.2, but we can perhaps attempt to make a set retroactively. It is a to-do for the Travis setup (http://github.com/JuliaCI/travis-build/issues/2) to allow version numbers in addition to `nightly` and `release`, but I think the furthest back for which we have generic Linux binaries is 0.3.1 or thereabouts. This will become very important as soon as we release 0.4.0, otherwise we'll lose 0.3 testing when `release` becomes 0.4 and `nightly` becomes 0.5-pre.

**Comment by stevengj** [comment]
I don't think it would be a disaster if we abandoned 0.2 support at this point, given that most 0.2 users are early Julia adopters who have probably upgraded if they are still using Julia.  (Although we should update the `REQUIRE` file then).   But I think it is absolutely critical to ensure that 0.3 is still tested when 0.4 is released.

**Comment by StefanKarpinski** [comment]
I agree that abandoning 0.2 seems reasonable at this point. I'm not aware of anyone using 0.2 Julia in any production sense.

**Comment by stevengj** [comment]
Even if we do abandon 0.2 support in Compat going forward, however, it is important that we tag at least one new release (or fix METADATA) that actually does support 0.2, in order for Pkg not to be utterly broken (because it will fetch the wrong Compat version right now) on any system that happens to be running 0.2.

**Comment by tkelman** [comment]
We could also go back through the history and find the most recent tagged version (of Compat, BinDeps, etc) which do work on 0.2, and modify the require's in metadata for any newer broken versions. Not sure which is less work.

**Comment by tkelman** [comment]
We could also go back through the history and find the most recent tagged version (of Compat, BinDeps, etc) which do work on 0.2, and modify the require's in metadata for any newer broken versions. Not sure which is less work.

**Comment by tkelman** [comment]
We could also go back through the history and find the most recent tagged version (of Compat, BinDeps, etc) which do work on 0.2, and modify the require's in metadata for any newer broken versions. Not sure which is less work.

**Comment by tkelman** [comment]
We could also go back through the history and find the most recent tagged version (of Compat, BinDeps, etc) which do work on 0.2, and modify the require's in metadata for any newer broken versions. Not sure which is less work.

**Comment by tkelman** [comment]
Sorry for the spam. Not sure what happened with github there.
