### ISSUE TITLE
Add isnothing to Compat

### ISSUE THREAD

**Issue by jlperla** [JuliaLang/Compat.jl#634]
https://github.com/JuliaLang/julia/blob/d40103336f5723de7f5600382977abbc36744f53/base/some.jl seems merged and stable.  Basically
```
"""
    isnothing(x)
Return `true` if `x === nothing`, and return `false` if not.
"""
isnothing(::Any) = false
isnothing(::Nothing) = true
```
If this added merged, then it would mean we could write lectures which use the new "best practice"?

**Comment by singularitti** [comment]
Can this pull request be merged?

**Comment by martinholters** [comment]
This is not a pull request.

**Comment by singularitti** [comment]
I am sorry. I mean, "can this issue be resolved"?

**Comment by martinholters** [comment]
Seems like a good opportunity for a first-time-contribution, if you want tackle it...

**Comment by singularitti** [comment]
This is actually not my first-time for a contribution. I used "pull request" because I think [@jlperla's comment](https://github.com/JuliaLang/Compat.jl/issues/634#issue-379294188) looks like a half-way pull request.
I do fork this repo. But when I look into the code, it is a little bit overwhelmed for me since it is not clear where to put these methods. So I do hope the maintainers could resolve this issue.
