### ISSUE TITLE
Precompilation Errors

### ISSUE THREAD

**Issue by arnavs** [JuliaLang/Compat.jl#636]
Whenever I try precompiling stuff, I get a ton of errors like: 

```
Module Compat with build ID 19540850339192894 is missing from the cache
```

Is this expected/normal? I thought `Compat.jl` supported precompilation.

**Comment by martinholters** [comment]
That is not normal and more likely a problem with Julia than with Compat.jl. What Julia version are you using?

**Comment by arnavs** [comment]
1.0.2

**Comment by martinholters** [comment]
Just tested locally with Julia 1.0.2 and Compat 1.4.0 and I have no issue at all. I've tried `using Compat` at the REPL, both with Compat already pre-compiled and without, as well as `using DSP` (as a package that supports precompilation and depends on Compat) in all four combinations of DSP and Compat already pre-compiled or not. I've never seen that error.

Under what circumstances exactly do you see the error?

Have you tried moving your `~/.julia/compiled/v1.0` folder out of the way? (You might want to keep it around instead of just deleting it to allow further investigation in case that fixes it.)

**Comment by phlavenk** [comment]
I 'm experiencing exactly the same issue. Even after deleting the .julia/compiled directory. Win64-1.0.2, compat 1.4.0
```julia
pkg"precompile"

Precompiling DataFrames
┌ Info: Precompiling DataFrames [a93c6f00-e57d-5684-b7b6-d8193f3e46c0]
└ @ Base loading.jl:1187
┌ Warning: Module Compat with build ID 30894928298315 is missing from the cache.
│ This may mean Compat [34da2185-b29b-5c13-b0c7-acf172513d20] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:941
```

**Comment by martinholters** [comment]
Ok, just to be sure, starting with a clean environment (`--project=/some/empty/directory`), and doing
```julia
using Pkg
pkg"add DataFrames"
pkg"precompile"
```
you get above error?

**Comment by arnavs** [comment]
Sorry, lost track of this for a bit. Will run this from a new Docker image and post results here.

**Comment by martinholters** [comment]
@arnavs, do you still see this? Can you give concrete steps how to reproduce within a clean environment?

**Comment by arnavs** [comment]
@martinholters Haven't seen it for a while (although once in a while it pops up? dunno). Have no clear steps to reproduce either...

We can close. But it would be good to track down what was happening here, too.
